spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:college}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:thisisaverysecretkeyforjwtsigningchangeit}
    expirationMs: ${JWT_EXPIRATION:86400000}

# Swagger UI at /swagger-ui/index.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
